.PHONY: clean All

All:
	@echo "----------Building project:[ facerec_video - Debug ]----------"
	@$(MAKE) -f  "facerec_video.mk"
clean:
	@echo "----------Cleaning project:[ facerec_video - Debug ]----------"
	@$(MAKE) -f  "facerec_video.mk" clean
