.PHONY: clean All

All:
	@echo "----------Building project:[ facerec_opencv - Debug ]----------"
	@$(MAKE) -f  "facerec_opencv.mk"
clean:
	@echo "----------Cleaning project:[ facerec_opencv - Debug ]----------"
	@$(MAKE) -f  "facerec_opencv.mk" clean
